wandb:
  log: True
  project: Segma debug
  name: train-whisperidou

data:
  dataset_path: data/baby_train
  classes: 
    - KCHI
    - OCH
    - MAL
    - FEM
    # - SPEECH

# necessary info for pred/eval
audio_config:
  chunk_duration_s: 4.0
  sample_rate: 16_000
  # True if pyannet, False if Whisper
  strict_frames: false

train:
  model: 
    name: whisperidou
  lr: 0.001
  batch_size: 32
  max_epochs: 100
  validation_metric: auroc
  # simple or advanced (python <= 3.11)
  profiler: null

  dataloader:
    num_workers: 64

  scheduler:
    patience: 3
