wandb:
  offline: false
  project:  hubert_longforms hydra surgical
  name: train

data:
  dataset_path: data/baby_train
  classes: 
    - KCHI
    - OCH
    - MAL
    - FEM

# necessary info for pred/eval
audio:
  chunk_duration_s: 4
  sample_rate: 16_000
  # True if pyannet, False if Whisper
  strict_frames: false

model:
  name: surgical_hubert_hydra
  #chkp_path : /home/tcharlot/coml/checkpoints

train:
  lr: 0.00001
  batch_size: 128
  max_epochs: 100
  validation_metric: loss
  # [loss, partial_loss, label_loss, f1_score, auroc, roc]
  # [loss (includes label_loss), f1_score]
  extra_val_metrics: [loss, f1_score]
  # simple or advanced (python <= 3.11)
  profiler: null

  dataloader:
    num_workers: 8

  scheduler:
    patience: 3
