wandb:
  offline: false
  project: surgical wavlm hydra debug
  name: train

data:
  dataset_path: data/debug_20
  classes: 
    - key_child
    - other_child
    - male
    - female
    # - SPEECH

# necessary info for pred/eval
audio:
  chunk_duration_s: 4.0
  sample_rate: 16_000
  # True if pyannet, False if Whisper
  strict_frames: false

model:
  name: surgical_wavlm_hydra

train:
  lr: 0.001
  batch_size: 32
  max_epochs: 100
  # validation_metric: auroc
  validation_metric: loss
  # [loss, partial_loss, label_loss, f1_score, auroc, roc]
  # [loss (includes label_loss), f1_score]
  extra_val_metrics: [loss, f1_score]
  # simple or advanced (python <= 3.11)
  profiler: null

  dataloader:
    num_workers: 8

  scheduler:
    patience: 3
