wandb:
  log: True
  project: Segma debug
  name: db_train

data:
  dataset_path: data/debug
  classes: 
    - male
    - female
    - key_child
    - other_child

# necessary info for pred/eval
audio_config:
  chunk_duration_s: 2.0
  sample_rate: 16_000
  strict_frames: true

train:
  model: 
    # name: whisperidou
    name: pyannet
  lr: 0.001
  batch_size: 16
  max_epochs: 40
  validation_metric: auroc
  # simple or advanced (python <= 3.11)
  profiler: null

  dataloader:
    num_workers: 8

  scheduler:
    patience: 3
