wandb:
  offline: true
  project: Segma debug
  name: db_train

data:
  dataset_path: data/debug_50
  classes: 
    - male
    - female
    - key_child
    - other_child

# necessary info for pred/eval
audio:
  chunk_duration_s: 2.0
  sample_rate: 16_000
  # True if pyannet, False if Whisper
  strict_frames: False

model: 
  name: surgical_hydra
  # name: hydra_whisper
  # name: whisperidou
  # name: surgical_whisper
  # name: pyannet
  # name: pyannet_slim

train:
  lr: 0.001
  batch_size: 16
  max_epochs: 40
  validation_metric: loss
  # validation_metric: f1_score, auroc
  extra_val_metrics: [loss]
  # simple or advanced (python <= 3.11)
  profiler: null

  dataloader:
    num_workers: 12

  scheduler:
    patience: 3
