name: Python Code Quality
on: [push] 
jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run ruff check .


  # TODO - missing sox backend -- maybe in pyproject.toml ?
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup
  #     - run: uv run pytest tests
